In [48]:
import numpy as np

## 1. Create a 3x3x3 array with random values 

In [18]:
arr = np.random.random((3,3,3))
print(arr)
print(arr.shape)

[[[0.5802265  0.70621698 0.82521604]
  [0.99943259 0.57970162 0.27643334]
  [0.19703554 0.99420755 0.88785629]]

 [[0.79248349 0.88628736 0.83958564]
  [0.19000569 0.33454226 0.42208255]
  [0.61137554 0.19546743 0.63031189]]

 [[0.44826098 0.30193727 0.34618805]
  [0.52897265 0.85324151 0.18770345]
  [0.55965897 0.85543851 0.61650791]]]
(3, 3, 3)


## 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [21]:
arr = np.diag(np.arange(4)+1, k = -1)
print (arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [23]:
a = np.zeros ((8,8), dtype=int)
print("Checkerboard Pattern")
a[1::2, ::2]= 1
a[::2, 1::2] = 1
print (a)

Checkerboard Pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4. Normalize a 5x5 random matrix

In [25]:
b = np.random.random((5,5))
bmax , bmin = b.max() , b.min()
b = (b - bmin) / (bmax - bmin)
print(b)

[[0.59092222 0.30987707 0.37487987 0.80626429 0.19122504]
 [0.15930578 0.         0.24394568 0.08099859 0.55848659]
 [1.         0.83505384 0.41387889 0.81447663 0.8442514 ]
 [0.32373529 0.65631911 0.27756727 0.25329264 0.84523551]
 [0.91728111 0.50499288 0.23680505 0.01450926 0.13539698]]


## 5.  How to find common values between two arrays?

In [29]:
arr1 = [1,2,3,4,5,6,7,8,9,10]
print("Array 1:  " , arr1)
arr2 = [2,4,6,8,10,12,14,16,18,20]
print("Array 2: " , arr2)
print("Common values between Array 1 & 2 are: " , np.intersect1d(arr1,arr2))

Array 1:   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Array 2:  [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
Common values between Array 1 & 2 are:  [ 2  4  6  8 10]


## 6.How to get the dates of yesterday, today and tomorrow?

In [30]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


## 7. Consider two random array A and B, check if they are equal

In [36]:
a1 = np.random.randint(0,2,5)
a2 = np.random.randint(0,2,5)
equal = np.allclose(a1,a2)
print(equal)

False


## 8.Create random vector of size 10 and replace the maximum value by 0 

In [38]:
v = np.random.random(10)
print(v)
v[v.argmax()] = 0
print(v)

[0.11828895 0.4156632  0.24526639 0.61151096 0.05186446 0.06808493
 0.77367492 0.19096107 0.82701444 0.11875049]
[0.11828895 0.4156632  0.24526639 0.61151096 0.05186446 0.06808493
 0.77367492 0.19096107 0.         0.11875049]


## 9. How to print all the values of an array?

In [47]:
d = np.random.random((10,10))
print(d)

[[0.60893948 0.21966346 0.95892623 0.93629437 0.25184865 0.22183096
  0.65716171 0.10129186 0.85664963 0.59937715]
 [0.64784543 0.14917049 0.00219103 0.27015281 0.54154224 0.20406327
  0.8669521  0.42981917 0.07183796 0.0555303 ]
 [0.42376949 0.75306663 0.53906766 0.64299339 0.5380479  0.11820849
  0.7094858  0.56143542 0.95069613 0.43051364]
 [0.03919256 0.45148163 0.30802323 0.04724182 0.43868457 0.60190077
  0.28289022 0.39599951 0.27079916 0.85896245]
 [0.21774113 0.72994976 0.20673567 0.14980656 0.82421188 0.93904741
  0.90146712 0.36283576 0.48372926 0.9416961 ]
 [0.6884863  0.57133623 0.68806687 0.28662129 0.90163263 0.44347406
  0.48013403 0.07359455 0.14973495 0.55693541]
 [0.76954782 0.31891972 0.23702551 0.7734658  0.33103781 0.42403059
  0.80637225 0.08299205 0.85822983 0.40617559]
 [0.38620947 0.73365201 0.9113921  0.97464106 0.84371707 0.83362469
  0.06317788 0.09484429 0.31548841 0.75142696]
 [0.9849279  0.87613523 0.50202914 0.72444742 0.81530378 0.96710898
  0.25343485

## 10.Subtract the mean of each row of a matrix

In [55]:
print("Original matrix:\n")
X = np.random.random((10, 10))
print(X)
print("\nFinal Matrix \n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.92949061 0.84942861 0.80228025 0.60030719 0.51099316 0.0126613
  0.22530083 0.99374109 0.31338106 0.07843195]
 [0.52125141 0.97675474 0.12255457 0.1953524  0.68040558 0.1028886
  0.00528695 0.31022549 0.25931086 0.86538947]
 [0.80529392 0.27398469 0.18970264 0.85556071 0.41698076 0.32662855
  0.33776613 0.40973748 0.87786662 0.9671849 ]
 [0.42812107 0.92997084 0.21064648 0.48326508 0.50729844 0.06456664
  0.64479641 0.11550953 0.06035983 0.93345757]
 [0.46461903 0.09397741 0.43894145 0.95813297 0.26501985 0.62079803
  0.75674617 0.43410992 0.04498274 0.18737021]
 [0.2673495  0.55311573 0.69343236 0.88167014 0.61448248 0.56203953
  0.14762184 0.29313443 0.30518716 0.97410422]
 [0.65461147 0.92175041 0.39965914 0.02509309 0.27463603 0.52967944
  0.80779048 0.8015942  0.45563818 0.1178835 ]
 [0.41849111 0.86885486 0.82919785 0.62151937 0.0238942  0.58960868
  0.04394227 0.29613469 0.17600774 0.963135  ]
 [0.15473753 0.20916719 0.98972043 0.29217589 0.73134566 0.55284

## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [56]:
e = np.ones(10)
I = np.random.randint(0,len(e),20)
e += np.bincount(I, minlength=len(e))
print(e)

[2. 5. 2. 2. 4. 3. 2. 4. 3. 3.]


## 12.How to get the diagonal of a dot product?

In [58]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.sum(A * B.T, axis=1)

array([12, 60, 37])

## 13.How to find the most frequent value in an array?

In [65]:
f = np.random.randint(0,10,50)
print (f)
most = np.bincount(f).argmax()
print('Most Frequent Value:' , most)

[4 8 3 2 7 7 9 0 7 0 8 8 2 4 8 8 7 5 2 7 7 2 1 9 1 6 4 7 5 0 2 1 7 2 3 8 3
 6 9 9 3 5 0 7 5 3 8 3 2 7]
Most Frequent Value: 7


## 14.How to get the n largest values of an array

In [68]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 8
print (Z[np.argpartition(-Z,n)[:n]])

[9993 9999 9994 9997 9996 9992 9995 9998]


## 15.How to create a record array from a regular array?

In [76]:
g = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(g.T,names='col1, col2, col3',formats = 'S8, f8, i8')

In [77]:
print(g)
print("\n",R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]

 [(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
