In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

C:\Users\narkh\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
cd C:\Users\narkh\Downloads\Datasets\Decision tree

C:\Users\narkh\Downloads\Datasets\Decision tree


In [3]:
data = pd.read_csv("train.csv")

In [4]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [8]:
le = preprocessing.LabelEncoder()

In [9]:
data["Sex"] = le.fit_transform(data["Sex"])
data["Embarked"] = le.fit_transform(data["Embarked"])

In [44]:
y = data["Survived"]
X = data[["Pclass","Sex","Embarked","SibSp","Parch"]]

In [45]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [46]:
from sklearn.naive_bayes import *

In [47]:
model = BernoulliNB()

In [48]:
model.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [49]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [50]:
ypred = model.predict(X_test)

In [51]:
accuracy_score(y_test,ypred,normalize=True)

0.7623318385650224

In [52]:
confusion_matrix(y_test,ypred)

array([[109,  23],
       [ 30,  61]], dtype=int64)

In [57]:
ypred = model.predict([[1,0,0,1,0]])
ypred

array([1], dtype=int64)

In [61]:
y = data["Pclass"]
X = data[["Survived","Sex","Embarked","SibSp","Parch"]]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [63]:
model1 = BernoulliNB()
model1.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [66]:
ypred = model1.predict(X_test)

In [67]:
accuracy_score(y_test,ypred,normalize=True)

0.57847533632287

In [68]:
ypred = model.predict([[1,0,0,1,0]])
ypred

array([1], dtype=int64)

In [77]:
y = data["Sex"]
X = data[["Survived","Pclass","Embarked","SibSp","Parch"]]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [70]:
model2 = BernoulliNB()
model2.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [74]:
ypred = model2.predict(X_test)

In [75]:
accuracy_score(y_test,ypred,normalize=True)

0.757847533632287

In [76]:
ypred = model.predict([[1,1,0,1,0]])
ypred

array([0], dtype=int64)

In [79]:
y = data["Embarked"]
X = data[["Survived","Pclass","Sex","SibSp","Parch"]]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [80]:
model3 = BernoulliNB()
model3.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [86]:
ypred = model3.predict(X_test)

In [87]:
accuracy_score(y_test,ypred,normalize=True)

0.03139013452914798

In [88]:
ypred = model.predict([[1,1,0,1,0]])
ypred

array([0], dtype=int64)

In [97]:
y = data["SibSp"]
X = data[["Survived","Pclass","Sex","Embarked","Parch"]]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [98]:
model4 = BernoulliNB()
model4.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [99]:
ypred = model4.predict(X_test)

In [100]:
accuracy_score(y_test,ypred,normalize=True)

0.6816143497757847

In [103]:
ypred = model4.predict([[0,3,1,2,0]])
ypred

array([0], dtype=int64)

In [109]:
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   
5                                   Moran, Mr. James    1  45.0      0      0   
6                            McCarthy, Mr. Timothy J    1  54.0      0      0   
7                     Palsson, Master. Gosta Leonard    1   2.0      3      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    0  27.0      0      2   
9                Nasser, Mrs. Nicholas (Adele Achem)    0  14.0      1      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2  
5            330877   8.4583   NaN         1  
6             17463  51.8625   E46         2  
7            349909  21.0750   NaN         2  
8            347742  11.1333   NaN         2  
9            237736  30.0708   NaN         0

In [104]:
y = data["Parch"]
X = data[["Survived","Pclass","Sex","Embarked","SibSp"]]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [105]:
model5 = BernoulliNB()
model5.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [106]:
ypred = model5.predict(X_test)

In [107]:
accuracy_score(y_test,ypred,normalize=True)

0.7085201793721974

In [110]:
ypred = model5.predict([[0,3,1,2,3]])
ypred

array([0], dtype=int64)